name:                gol-haskell
version:             0.1.0.0
github:              "hex0x0000/gol-haskell"
license:             GPL3
author:              "hex0x0000"
maintainer:          "hex0x0000@protonmail.com"
copyright:           "2022 hex0x0000"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hex0x0000/gol-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- process
- bytestring

library:
  source-dirs: src

executables:
  gol-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gol-haskell

tests:
  gol-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gol-haskell
